project:
  type: website
  output-dir: output
  
author:
  - name: Stefan Bringuier
    affiliations:
      - name: Materials Scientist
        department: Independent Researcher
        address: 
        city: 
        country: USA
        postal-code: 00000
    orcid: 0000-0001-6753-1437
    email: stefanbringuier@gmail.com
    url: https://stefanbringuier.info
    corrresponding: true

abstract: >
 This document provides basic review of superconducting materials from a materials science \& engineering perspective. This entails a very basic review of conductivity, magnetism, and superconductivity theory. The remainder is focused on aspects of specific material systems, such as compositional phases that exhibit superconducting phase, mechanical properties, and processing. High-level review of applications is also provided. The intent of this document is to act as a quick digest for someone who plans to dive deeper into the provided references.

keywords:
  - Superconductors
  - Materials Science

bibliography: _references/references.bib

copyright: 
  holder: Stefan Bringuier

citation: true

license: "CC BY-SA"

date: today
date-format: medium